/**
 * El documento antes de tener formato.
 *
 * Lo que las dos exportaciones comparten y por lo que no pueden divergir: las
 * palabras, qué anotaciones viajan, en qué orden van numeradas y cómo se llama
 * el fichero. Vivía en `latexExport.js` porque el `.tex` fue primero; el PDF lo
 * importaba de allí y eso convertía al emisor de LaTeX en el módulo compartido
 * sin decirlo. Aquí no hay nada de LaTeX ni de DOM.
 */

const COPY = {
  es: {
    babel: 'spanish,es-nodecimaldot,es-noquoting',
    stamp: level => `Versión en lenguaje sencillo · nivel ${level}`,
    abstract: 'Reescritura en lenguaje sencillo del artículo original, generada automáticamente y anotada por el lector. El texto de abajo no es obra del autor del artículo: parafrasea sus resultados y no los sustituye.',
    provenance: 'Reescrito por PaperTok. No es obra de sus autores',
    mine: 'Tuya',
    ai: 'IA',
    levels: { beginner: 'principiante', university: 'universitario', researcher: 'investigador' },
    fontHint: 'Descomenta las dos líneas siguientes si tienes Newsreader instalada.',
    kindNote: ['El marcador de una nota es el mismo venga de quien venga; lo que las', 'distingue es la etiqueta con la que empieza la nota.'],
    footerNote: ['La procedencia no es una de las notas: va al pie de CADA página, fuera', 'de la numeración, porque el fichero puede acabar lejos de aquí.'],
    generated: 'Generado por PaperTok. Compila con pdflatex o xelatex.',
    masthead: 'PaperTok · Versión en lenguaje sencillo',
    levelStamp: level => `Nivel ${level}`,
    noticeLabel: 'Aviso',
    sourcePrefix: 'Artículo original',
    colophonHeading: 'Procedencia',
    colophonKeys: {
      title: 'Artículo original',
      authors: 'Autoría',
      source: 'Fuente',
      version: 'Esta versión',
      annotated: 'Anotado con',
    },
    versionValue: (level, date) => `Lenguaje sencillo, nivel ${level} · ${date}`,
    // Ni «0 subrayados» ni «0 notas»: la mitad que vale cero no se imprime. Un
    // documento solo marcado y otro solo anotado son los dos casos normales.
    annotatedWith: ({ marks, mine, ai }) => {
      const notes = mine + ai;
      if (marks + notes === 0) return 'Sin subrayados ni notas';
      const left = marks ? `${marks} ${marks === 1 ? 'subrayado' : 'subrayados'}` : '';
      const right = notes
        ? `${notes} ${notes === 1 ? 'nota' : 'notas'}: ${mine} del lector, ${ai} de la IA`
        : '';
      return [left, right].filter(Boolean).join(' y ');
    },
  },
  en: {
    babel: 'english',
    stamp: level => `Plain-language version · ${level} level`,
    abstract: 'A plain-language rewrite of the original article, generated automatically and annotated by its reader. The text below is not the work of the article’s author: it paraphrases the results and does not replace them.',
    provenance: 'Rewritten by PaperTok. Not the work of its authors',
    mine: 'Yours',
    ai: 'AI',
    levels: { beginner: 'beginner', university: 'university', researcher: 'researcher' },
    fontHint: 'Uncomment the next two lines if you have Newsreader installed.',
    kindNote: ['A note\'s marker is the same whoever wrote it; what tells them apart', 'is the label the note itself starts with.'],
    footerNote: ['Provenance is not one of the notes: it sits at the foot of EVERY page,', 'outside their numbering, because this file can end up a long way from here.'],
    generated: 'Generated by PaperTok. Compile with pdflatex or xelatex.',
    masthead: 'PaperTok · Plain-language version',
    levelStamp: level => `${level.charAt(0).toUpperCase()}${level.slice(1)} level`,
    noticeLabel: 'Notice',
    sourcePrefix: 'Original article',
    colophonHeading: 'Provenance',
    colophonKeys: {
      title: 'Original article',
      authors: 'Authors',
      source: 'Source',
      version: 'This version',
      annotated: 'Annotated with',
    },
    versionValue: (level, date) => `Plain language, ${level} level · ${date}`,
    annotatedWith: ({ marks, mine, ai }) => {
      const notes = mine + ai;
      if (marks + notes === 0) return 'No highlights or notes';
      const left = marks ? `${marks} ${marks === 1 ? 'highlight' : 'highlights'}` : '';
      const right = notes
        ? `${notes} ${notes === 1 ? 'note' : 'notes'}: ${mine} yours, ${ai} from the AI`
        : '';
      return [left, right].filter(Boolean).join(' and ');
    },
  },
};

/**
 * A filename the operating system will accept, derived from the title so the
 * download is recognisable in a folder six months later.
 */
export function exportFileName(paper, language = 'es', extension = 'tex') {
  const stem = String(paper?.title || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60)
    .replace(/-+$/g, '');
  const suffix = language === 'en' ? 'plain-words' : 'en-simple';
  return `${stem || 'paper'}-${suffix}.${extension}`;
}

/**
 * The document's words, shared with the PDF export so the two formats can
 * never drift apart: one provenance line, one stamp, one pair of note labels.
 */
export function documentCopy(language = 'es') {
  return COPY[language === 'en' ? 'en' : 'es'];
}

/**
 * La fecha, en el idioma del documento.
 *
 * `Intl` es el único sitio donde el documento depende de la máquina que lo
 * hace. Una fecha inválida devuelve cadena vacía en vez de «Invalid Date»
 * impreso en la portada: la línea se queda sin fecha, que es mucho menos malo.
 */
export function formatExportDate(value, language = 'es') {
  // `new Date(null)` is not an invalid date, it is the Unix epoch: `null`
  // coerces to `0` before the constructor ever sees it. Ruled out by hand so
  // a missing date does not print as 1 de enero de 1970.
  if (value == null) return '';
  const date = value instanceof Date ? value : new Date(value);
  if (Number.isNaN(date.getTime())) return '';
  return new Intl.DateTimeFormat(language === 'en' ? 'en-GB' : 'es-ES', {
    day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC',
  }).format(date);
}

/** Los autores como una línea de texto: hasta `limit` nombres, luego honestidad. */
export function bylineText(paper, limit = 12) {
  const names = (Array.isArray(paper?.authors) ? paper.authors : [])
    .map(author => String(author?.name || author || '').trim())
    .filter(Boolean);
  if (names.length === 0) return '';
  const shown = names.slice(0, limit).join(', ');
  return names.length > limit ? `${shown} et al.` : shown;
}

/**
 * El título tal como va a la fila del colofón: hasta `limit` caracteres,
 * luego honestidad — el mismo trato que ya recibe la autoría, arriba.
 *
 * Solo esta fila lo necesita. El título de portada (`documentMeta`'s
 * `title`) se queda sin tope a propósito: ese título es un párrafo normal y
 * una página normal SÍ se parte donde haga falta. La fila del colofón no:
 * vive dentro de un `\minipage` que no puede partirse por dentro (LaTeX
 * exporter, Task 6), así que un título sin límite ahí no se ve feo — deja de
 * caber en ninguna página, capadas o no, y compilado eso salió como texto
 * solapado e ilegible mucho antes de que un título real pudiera acercarse al
 * límite. Ningún título de paper de verdad se acerca a los 500 caracteres;
 * esto es una defensa para el caso patológico, no un recorte pensado para
 * verse.
 *
 * `runningTitle`, más abajo, es distinto: ese SÍ se ve recortado en el uso
 * normal, por una razón distinta — ver su propio comentario.
 */
export function colophonTitleText(paper, limit = 500) {
  const title = String(paper?.title || '');
  return title.length > limit ? `${title.slice(0, limit).trimEnd()}…` : title;
}

/**
 * El título tal como va a la cabecera de cada página de continuación
 * (`\fancyhead[L]`, latexExport.js): hasta `limit` caracteres, luego
 * honestidad — el mismo mecanismo que `colophonTitleText`, arriba, un límite
 * distinto porque el motivo es distinto.
 *
 * `\fancyhead[L]` (este título) y `\fancyhead[R]` (`\leftmark`, que lleva el
 * número de sección y su encabezado — ver `sectionMarkText`, latexExport.js)
 * son dos zonas sin ajuste de línea ni control de colisión: cuando sus
 * anchuras naturales suman más que el hueco entre ellas, se IMPRIMEN UNA
 * ENCIMA DE LA OTRA en vez de truncarse — compilado con un título de 102
 * caracteres (no especialmente largo) y mirada la página, resultó
 * ilegible, sin un solo aviso de `Overfull`/`Underfull`. Un caso más suave
 * —el título envolviendo a dos líneas— sí avisa (`fancyhdr Warning:
 * \headheight is too small`), pero tampoco es el resultado que se quiere.
 *
 * El límite se midió, no se adivinó: `\ptmono\scriptsize` (la tipografía de
 * esta cabecera) es monoespaciada de verdad a este tamaño — confirmado
 * imprimiendo el ancho de letras, dígitos y cada comando de `PUNCTUATION`
 * (incluidos los que este mismo cambio corrige) con `\settowidth`: los
 * 4,25pt exactos, sin excepción. El `\textwidth` de esta separata
 * (`preamble()`'s `geometry`) mide 441,02pt, es decir, unas 103 celdas de
 * ese ancho. De esas 103: 6 se reservan para el prefijo de la zona derecha
 * en el peor caso (`999\ \textperiodcentered\ `, tres dígitos de sección),
 * 45 para este título y 30 para `sectionMarkText` — quedan unas 22 celdas
 * (~97pt) de hueco garantizado entre las dos zonas aun cuando las dos
 * lleguen a su tope a la vez, muchas veces el ancho de un solo carácter:
 * las dos zonas no pueden tocarse. El título recibe algo más de presupuesto
 * que el encabezado de sección porque es el elemento más importante de las
 * dos cabeceras —de qué paper es esto— mientras que la de sección es una
 * ayuda de orientación más corta por naturaleza.
 */
export function runningTitleText(paper, limit = 45) {
  const title = String(paper?.title || '');
  return title.length > limit ? `${title.slice(0, limit).trimEnd()}…` : title;
}

/**
 * Todo lo que el documento dice de sí mismo, ya montado en frases.
 *
 * Es el sitio donde los dos formatos no pueden divergir: el emisor de LaTeX y
 * el de DOM reciben cadenas y las colocan, ninguno de los dos compone. Las
 * filas del colofón se omiten cuando no hay dato en vez de imprimirse vacías,
 * porque medio arXiv no trae DOI y una fila «Fuente: —» no informa de nada.
 */
export function documentMeta({
  paper, language = 'es', level = 'university', originalUrl = '',
  generatedAt = new Date(), counts = { marks: 0, mine: 0, ai: 0 },
} = {}) {
  const copy = documentCopy(language);
  const levelName = copy.levels[level] || level;
  const date = formatExportDate(generatedAt, language);
  const title = String(paper?.title || '');
  const byline = bylineText(paper);
  const url = String(originalUrl || '');

  const source = [url && `${copy.sourcePrefix}: ${url}`, date].filter(Boolean).join(' · ');

  const rows = [
    { key: copy.colophonKeys.title, value: colophonTitleText(paper) },
    { key: copy.colophonKeys.authors, value: byline },
    { key: copy.colophonKeys.source, value: url },
    { key: copy.colophonKeys.version, value: copy.versionValue(levelName, date) },
    { key: copy.colophonKeys.annotated, value: copy.annotatedWith(counts) },
  ].filter(row => row.value);

  return {
    masthead: copy.masthead,
    level: copy.levelStamp(levelName),
    title,
    byline,
    source,
    noticeLabel: copy.noticeLabel,
    notice: copy.abstract,
    provenance: copy.provenance,
    runningTitle: runningTitleText(paper),
    colophon: { heading: copy.colophonHeading, rows },
  };
}

/**
 * Numbers every annotation that carries words, in document order, and hands
 * back a lookup by paragraph. A bare highlight has nothing to say in a footnote
 * and is not given a number — it is just colour on the page.
 */
export function numberAnnotations(sections, annotations) {
  const order = new Map();
  sections.forEach((section, index) => order.set(String(section?.id), index));
  const placed = annotations
    .filter(item => item && item.quote)
    .map((item, arrival) => ({ item, arrival }))
    .sort((left, right) => {
      const ls = order.has(String(left.item.sectionId)) ? order.get(String(left.item.sectionId)) : Number.MAX_SAFE_INTEGER;
      const rs = order.has(String(right.item.sectionId)) ? order.get(String(right.item.sectionId)) : Number.MAX_SAFE_INTEGER;
      if (ls !== rs) return ls - rs;
      const lp = Number(left.item.paragraphIndex) || 0;
      const rp = Number(right.item.paragraphIndex) || 0;
      if (lp !== rp) return lp - rp;
      return left.arrival - right.arrival;
    });

  const byParagraph = new Map();
  const numbered = [];
  for (const { item } of placed) {
    const entry = { ...item };
    if (item.note) {
      entry.number = numbered.length + 1;
      numbered.push(entry);
    }
    const key = `${item.sectionId}:${Number(item.paragraphIndex) || 0}`;
    byParagraph.set(key, [...(byParagraph.get(key) || []), entry]);
  }
  return { byParagraph, numbered };
}

/**
 * The annotations this rewrite can actually carry.
 *
 * The rail holds every annotation for the paper, at any level and in any
 * language; the marks in the text are filtered to the rewrite on screen. An
 * export that used the rail's list put notes written on other words into a
 * document that no longer contains them — anchored by quote, a note only means
 * anything in the rewrite it was made on.
 *
 * An annotation with no level recorded predates the field and is kept: dropping
 * it would delete history rather than filter it.
 */
export function exportableAnnotations(annotations = [], { sections = [], level, language } = {}) {
  const known = new Set(sections.map(section => String(section?.id)));
  const wanted = language === 'en' ? 'en' : 'es';
  return annotations.filter(item => {
    if (!item?.quote) return false;
    if (level && item.level && item.level !== level) return false;
    if (item.language && item.language !== wanted) return false;
    return known.has(String(item.sectionId));
  });
}

/** What the export card counts, without building the document to find out. */
export function summarizeExport(annotations = []) {
  let marks = 0;
  let mine = 0;
  let ai = 0;
  for (const item of annotations) {
    if (!item?.quote) continue;
    if (item.kind === 'ai') ai += 1;
    else if (item.note) mine += 1;
    else marks += 1;
  }
  return { marks, mine, ai };
}
