/**
 * El documento antes de tener formato.
 *
 * Lo que las dos exportaciones comparten y por lo que no pueden divergir: las
 * palabras, qué anotaciones viajan, en qué orden van numeradas y cómo se llama
 * el fichero. Vivía en `latexExport.js` porque el `.tex` fue primero; el PDF lo
 * importaba de allí y eso convertía al emisor de LaTeX en el módulo compartido
 * sin decirlo. Aquí no hay nada de LaTeX ni de DOM.
 */

const COPY = {
  es: {
    babel: 'spanish,es-nodecimaldot,es-noquoting',
    stamp: level => `Versión en lenguaje sencillo · nivel ${level}`,
    abstract: 'Reescritura en lenguaje sencillo del artículo original, generada automáticamente y anotada por el lector. El texto de abajo no es obra del autor del artículo: parafrasea sus resultados y no los sustituye.',
    provenance: 'Reescrito por PaperTok. No es obra de sus autores',
    mine: 'Tuya',
    ai: 'IA',
    levels: { beginner: 'principiante', university: 'universitario', researcher: 'investigador' },
    fontHint: 'Descomenta las dos líneas siguientes si tienes Newsreader instalada.',
    kindNote: ['El marcador de una nota es el mismo venga de quien venga; lo que las', 'distingue es la etiqueta con la que empieza la nota.'],
    footerNote: ['La procedencia no es una de las notas: va al pie de CADA página, fuera', 'de la numeración, porque el fichero puede acabar lejos de aquí.'],
    generated: 'Generado por PaperTok. Compila con pdflatex o xelatex.',
  },
  en: {
    babel: 'english',
    stamp: level => `Plain-language version · ${level} level`,
    abstract: 'A plain-language rewrite of the original article, generated automatically and annotated by its reader. The text below is not the work of the article’s author: it paraphrases the results and does not replace them.',
    provenance: 'Rewritten by PaperTok. Not the work of its authors',
    mine: 'Yours',
    ai: 'AI',
    levels: { beginner: 'beginner', university: 'university', researcher: 'researcher' },
    fontHint: 'Uncomment the next two lines if you have Newsreader installed.',
    kindNote: ['A note\'s marker is the same whoever wrote it; what tells them apart', 'is the label the note itself starts with.'],
    footerNote: ['Provenance is not one of the notes: it sits at the foot of EVERY page,', 'outside their numbering, because this file can end up a long way from here.'],
    generated: 'Generated by PaperTok. Compile with pdflatex or xelatex.',
  },
};

/**
 * A filename the operating system will accept, derived from the title so the
 * download is recognisable in a folder six months later.
 */
export function exportFileName(paper, language = 'es', extension = 'tex') {
  const stem = String(paper?.title || '')
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60)
    .replace(/-+$/g, '');
  const suffix = language === 'en' ? 'plain-words' : 'en-simple';
  return `${stem || 'paper'}-${suffix}.${extension}`;
}

/**
 * The document's words, shared with the PDF export so the two formats can
 * never drift apart: one provenance line, one stamp, one pair of note labels.
 */
export function documentCopy(language = 'es') {
  return COPY[language === 'en' ? 'en' : 'es'];
}

/**
 * Numbers every annotation that carries words, in document order, and hands
 * back a lookup by paragraph. A bare highlight has nothing to say in a footnote
 * and is not given a number — it is just colour on the page.
 */
export function numberAnnotations(sections, annotations) {
  const order = new Map();
  sections.forEach((section, index) => order.set(String(section?.id), index));
  const placed = annotations
    .filter(item => item && item.quote)
    .map((item, arrival) => ({ item, arrival }))
    .sort((left, right) => {
      const ls = order.has(String(left.item.sectionId)) ? order.get(String(left.item.sectionId)) : Number.MAX_SAFE_INTEGER;
      const rs = order.has(String(right.item.sectionId)) ? order.get(String(right.item.sectionId)) : Number.MAX_SAFE_INTEGER;
      if (ls !== rs) return ls - rs;
      const lp = Number(left.item.paragraphIndex) || 0;
      const rp = Number(right.item.paragraphIndex) || 0;
      if (lp !== rp) return lp - rp;
      return left.arrival - right.arrival;
    });

  const byParagraph = new Map();
  const numbered = [];
  for (const { item } of placed) {
    const entry = { ...item };
    if (item.note) {
      entry.number = numbered.length + 1;
      numbered.push(entry);
    }
    const key = `${item.sectionId}:${Number(item.paragraphIndex) || 0}`;
    byParagraph.set(key, [...(byParagraph.get(key) || []), entry]);
  }
  return { byParagraph, numbered };
}

/**
 * The annotations this rewrite can actually carry.
 *
 * The rail holds every annotation for the paper, at any level and in any
 * language; the marks in the text are filtered to the rewrite on screen. An
 * export that used the rail's list put notes written on other words into a
 * document that no longer contains them — anchored by quote, a note only means
 * anything in the rewrite it was made on.
 *
 * An annotation with no level recorded predates the field and is kept: dropping
 * it would delete history rather than filter it.
 */
export function exportableAnnotations(annotations = [], { sections = [], level, language } = {}) {
  const known = new Set(sections.map(section => String(section?.id)));
  const wanted = language === 'en' ? 'en' : 'es';
  return annotations.filter(item => {
    if (!item?.quote) return false;
    if (level && item.level && item.level !== level) return false;
    if (item.language && item.language !== wanted) return false;
    return known.has(String(item.sectionId));
  });
}

/** What the export card counts, without building the document to find out. */
export function summarizeExport(annotations = []) {
  let marks = 0;
  let mine = 0;
  let ai = 0;
  for (const item of annotations) {
    if (!item?.quote) continue;
    if (item.kind === 'ai') ai += 1;
    else if (item.note) mine += 1;
    else marks += 1;
  }
  return { marks, mine, ai };
}
